DO $$
BEGIN
  BEGIN EXECUTE 'GRANT REFERENCES, TRIGGER, SELECT ON TABLE auth.users TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT USAGE ON SCHEMA auth, storage, extensions TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT anon, authenticated, service_role TO sandbox_exec WITH ADMIN OPTION'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT supabase_storage_admin TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT pg_read_all_data, pg_write_all_data TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
END $$;