import type * as React from "react"

export const brand = {
  SITE_NAME: 'Tejaraa',
  SITE_URL: 'https://tejaraa.com',
  navy: '#0B1A33',
  navyDark: '#06101F',
  gold: '#D4A24A',
  goldSoft: '#F2D58A',
  text: '#1F2937',
  muted: '#6B7280',
  border: '#E5E7EB',
  bg: '#ffffff',
  panel: '#F8FAFC',
}

export const styles: Record<string, React.CSSProperties> = {
  main: {
    backgroundColor: brand.bg,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    margin: 0,
    padding: 0,
  },
  container: { maxWidth: '600px', margin: '0 auto', padding: '24px 16px' },
  header: {
    background: `linear-gradient(135deg, ${brand.navyDark} 0%, ${brand.navy} 100%)`,
    padding: '28px 32px',
    textAlign: 'center' as const,
    borderRadius: '12px 12px 0 0',
  },
  brand: {
    color: brand.gold,
    fontSize: '24px',
    fontWeight: 700,
    letterSpacing: '0.5px',
    margin: 0,
  },
  brandTag: {
    color: '#9DB0CC',
    fontSize: '11px',
    margin: '4px 0 0',
    letterSpacing: '1.5px',
    textTransform: 'uppercase' as const,
  },
  body: {
    backgroundColor: brand.bg,
    padding: '32px 32px 24px',
    border: `1px solid ${brand.border}`,
    borderTop: 'none',
    borderRadius: '0 0 12px 12px',
  },
  h1: {
    color: brand.navy,
    fontSize: '20px',
    fontWeight: 700,
    margin: '0 0 16px',
    lineHeight: 1.3,
  },
  text: {
    color: brand.text,
    fontSize: '15px',
    lineHeight: 1.6,
    margin: '0 0 16px',
  },
  muted: {
    color: brand.muted,
    fontSize: '13px',
    lineHeight: 1.5,
    margin: '16px 0 0',
  },
  link: { color: brand.navy, textDecoration: 'underline' },
  button: {
    backgroundColor: brand.navy,
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 600,
    padding: '12px 28px',
    borderRadius: '8px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  buttonGold: {
    backgroundColor: brand.gold,
    color: brand.navyDark,
    fontSize: '14px',
    fontWeight: 700,
    padding: '12px 28px',
    borderRadius: '8px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  code: {
    fontFamily: 'Courier, monospace',
    fontSize: '28px',
    fontWeight: 700,
    color: brand.navy,
    backgroundColor: brand.panel,
    border: `1px solid ${brand.border}`,
    borderLeft: `3px solid ${brand.gold}`,
    borderRadius: '8px',
    padding: '16px 24px',
    textAlign: 'center' as const,
    letterSpacing: '4px',
    margin: '16px 0 24px',
  },
  footer: {
    color: brand.muted,
    fontSize: '12px',
    lineHeight: 1.5,
    textAlign: 'center' as const,
    padding: '24px 16px 8px',
  },
  footerLink: { color: brand.muted, textDecoration: 'underline' },
}
