CREATE EXTENSION IF NOT EXISTS pg_net SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgmq;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
GRANT ALL ON SCHEMA public TO sandbox_exec;
GRANT USAGE, CREATE ON SCHEMA public TO sandbox_exec;
DO $$
BEGIN
  BEGIN EXECUTE 'GRANT anon, authenticated, service_role TO sandbox_exec WITH ADMIN OPTION'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT REFERENCES, TRIGGER, SELECT ON TABLE auth.users TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT USAGE ON SCHEMA auth, storage, extensions, cron, pgmq TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT ALL ON ALL TABLES IN SCHEMA cron TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cron TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT ALL ON ALL TABLES IN SCHEMA pgmq TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA pgmq TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT supabase_storage_admin TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT supabase_auth_admin TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT pg_read_all_data, pg_write_all_data TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT postgres TO sandbox_exec'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
  BEGIN EXECUTE 'GRANT sandbox_exec TO postgres'; EXCEPTION WHEN OTHERS THEN RAISE NOTICE '%', SQLERRM; END;
END $$;
CREATE OR REPLACE FUNCTION public.__import_exec(sql text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
BEGIN EXECUTE sql; END;
$fn$;
REVOKE ALL ON FUNCTION public.__import_exec(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.__import_exec(text) TO sandbox_exec;